import type { PageContent } from '@/content/types';

export const commercialIndustrial: PageContent = {
  slug: '/commercial-industrial-bess-malaysia',
  seoTitle: 'Commercial & Industrial BESS Malaysia | C&I Storage | Solunar',
  metaDescription:
    'Solunar designs Commercial & Industrial BESS in Malaysia — peak shaving, power expansion, solar storage, backup and resilience for factories, malls and data centres.',
  navLabel: 'Commercial & Industrial BESS',
  eyebrow: 'Solutions · C&I',
  h1: 'Reduce Maximum Demand Charges. Expand Power Capacity. Strengthen Energy Resilience.',
  lead: 'Solunar helps factories, commercial buildings, industrial facilities and large power users deploy advanced Battery Energy Storage Systems to reduce peak demand, support power expansion and improve energy cost control.',
  heroActions: [{ label: 'Speak to Our BESS Team', href: '/contact' }],
  image: {
    src: '/images/commercial-industrial-bess.png',
    alt: 'Commercial & industrial BESS cabinets beside a factory with rooftop solar in Malaysia',
    aspect: '4 / 3',
  },
  primaryKeyword: 'commercial BESS Malaysia',
  schema: { type: 'Service', serviceType: 'Commercial and industrial BESS support' },
  blocks: [
    {
      kind: 'prose',
      heading: 'Electricity cost is no longer just about consumption',
      paragraphs: [
        'For many commercial and industrial users in Malaysia, the electricity bill is no longer driven by energy consumption alone. Maximum demand charges, limited incoming capacity and the cost of grid upgrades now shape the true cost of power.',
        'As factories expand production, install more machinery, add EV chargers or increase cooling load, many sites hit the same wall: the available power supply is not enough, and upgrading it can be costly, slow and complex.',
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'What C&I energy users are facing',
      lead: 'Commercial and industrial sites across Malaysia share a common set of pressures:',
      items: [
        'Higher maximum demand charges',
        'Limited incoming power capacity',
        'Expensive TNB power-upgrade requirements',
        'Operational risk from power interruptions',
        'Pressure to integrate solar, EV charging and electrification',
        'Difficulty justifying large upfront CAPEX for energy infrastructure',
      ],
    },
    {
      kind: 'image',
      src: '/images/ci-detail.png',
      alt: 'Factory and mall rooftop solar with a commercial battery storage cabinet alongside',
      aspect: '16 / 9',
      caption:
        'Storage at the point of use — cutting demand charges, lifting solar self-consumption and adding resilience.',
    },
    {
      kind: 'prose',
      heading: 'The Solunar solution',
      paragraphs: [
        'Solunar provides integrated Commercial & Industrial BESS solutions designed to help businesses manage power intelligently. We do not only supply batteries — we design a complete, bankable and operational BESS solution around your load, tariff and growth plans.',
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'What a C&I BESS can do for you',
      lead: 'A well-designed system turns energy from a fixed cost into a managed asset:',
      items: [
        'Reduce maximum demand charges through peak shaving',
        'Store solar energy and discharge during high-demand periods',
        'Support power expansion without immediately upgrading the grid',
        'Improve power stability for critical operations',
        'Enable future EV charging, automation and electrification',
        'Improve energy resilience and business continuity',
      ],
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'What we provide',
      lead: 'Solunar supports C&I customers, solar EPCCs, project developers and financiers with:',
      items: [
        'BESS system design and sizing',
        'Battery container or cabinet solution',
        'PCS and inverter integration',
        'EMS and control system integration',
        'Solar + BESS hybrid design',
        'Maximum demand peak shaving strategy',
        'Load profile analysis',
        'Project feasibility support',
        'Installation partner coordination',
        'Testing and commissioning support',
        'Remote monitoring and performance tracking',
        'Long-term O&M support',
      ],
    },
    {
      kind: 'prose',
      heading: 'Designed for real business outcomes',
      paragraphs: [
        'Our BESS systems are not designed as standalone equipment. They are designed to solve business problems.',
        'For industrial customers, that can mean reducing monthly maximum demand charges. For commercial buildings, managing peak load from air-conditioning, tenants and EV chargers. For factories, expanding production capacity without waiting for costly infrastructure upgrades. For solar owners, improving self-consumption and reducing exported or wasted solar energy.',
      ],
    },
    {
      kind: 'cards',
      heading: 'C&I BESS use cases',
      lead: 'The same battery can serve several roles depending on how the EMS is configured:',
      columns: 3,
      items: [
        { icon: 'gauge', title: 'Maximum demand peak shaving', text: 'Discharge during peak periods to reduce the maximum demand the utility records.' },
        { icon: 'expansion', title: 'Power expansion support', text: 'Add usable load when existing grid capacity is constrained — without waiting for upgrades.' },
        { icon: 'sun', title: 'Solar energy storage', text: 'Store excess solar generation and use it when the building needs it most.' },
        { icon: 'safety', title: 'Backup & resilience', text: 'Support critical loads and reduce disruption during power instability.' },
        { icon: 'ev-charging', title: 'EV charging support', text: 'Enable higher-capacity EV charging without overstressing the site supply.' },
      ],
    },
    {
      kind: 'faq',
      items: [
        {
          question: 'How quickly can a C&I BESS pay back?',
          answer:
            'Payback depends on your maximum-demand charges, tariff, load profile, system size and operating strategy. Solunar models this per site rather than promising a fixed figure.',
        },
        {
          question: 'Can BESS work with our existing solar?',
          answer:
            'Yes. BESS pairs with existing or new rooftop solar to store excess generation, lift self-consumption and shave demand — coordinated through the EMS.',
        },
        {
          question: 'Do we need to upgrade our grid connection first?',
          answer:
            'Often not immediately. A BESS can supply additional peak power on demand, supporting expansion while any longer-term grid upgrade is planned.',
        },
      ],
    },
    {
      kind: 'prose',
      heading: 'Why Solunar',
      paragraphs: [
        'Solunar is a specialist BESS system integrator and energy storage solutions partner. We support EPCCs, solar developers, property owners, industrial customers and infrastructure investors with a complete solution covering technology selection, system integration, monitoring and long-term performance.',
        'Our strength is integrating batteries, PCS, EMS, solar PV, electrical infrastructure and operational strategy into one working system.',
      ],
    },
    {
      kind: 'cta',
      heading: 'Your electricity bill is changing. Your power demand is growing.',
      text: 'Talk to Solunar about how C&I BESS can help your business reduce cost, expand capacity and prepare for the next phase of electrification.',
      actions: [
        { label: 'Speak to Our BESS Team', href: '/contact' },
        { label: 'How Peak Shaving Works', href: '/peak-shaving-malaysia' },
      ],
    },
  ],
};

export const utilityScale: PageContent = {
  slug: '/utility-scale-ess-malaysia',
  seoTitle: 'Utility-Scale ESS Malaysia | LSS, CRESS & Grid-Scale BESS | Solunar',
  metaDescription:
    'Solunar delivers bankable utility-scale ESS solutions for LSS, CRESS and grid-connected projects — battery selection, PCS/EMS/SCADA, grid compliance, safety and O&M.',
  navLabel: 'Utility-Scale ESS Farms',
  eyebrow: 'Solutions · Utility-Scale',
  h1: 'Bankable Energy Storage for Large-Scale Solar, CRESS, LSS and Grid-Connected Projects',
  lead: 'Solunar supports developers, EPCCs, infrastructure funds, utilities and asset owners with integrated Utility-Scale Energy Storage System solutions for large renewable energy and grid-connected projects.',
  heroActions: [{ label: 'Explore Utility-Scale ESS Solutions', href: '/contact' }],
  image: {
    src: '/images/utility-scale-ess.png',
    alt: 'Rows of utility-scale BESS containers at a solar farm in Malaysia',
    aspect: '4 / 3',
  },
  primaryKeyword: 'utility-scale ESS Malaysia',
  schema: { type: 'Service', serviceType: 'Utility-scale ESS technology support' },
  blocks: [
    {
      kind: 'prose',
      heading: 'The market opportunity',
      paragraphs: [
        "Malaysia's renewable energy sector is entering a new phase. As large-scale solar, CRESS, data-centre power demand and grid-connected renewable projects grow, energy storage is becoming a critical part of the power infrastructure ecosystem.",
        'Solar alone is no longer enough. The market now needs solutions that manage intermittency, improve grid stability, support dispatchability and strengthen renewable project economics — which is where utility-scale ESS becomes essential.',
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'Challenges at utility scale',
      lead: 'Large-scale renewable developers face a recurring set of challenges:',
      items: [
        'Solar generation is intermittent',
        'Grid connection capacity can be limited',
        'Energy output may not match demand timing',
        'Bankability depends on reliable long-term performance',
        'Investors and banks need proven technology and clear risk management',
        'O&M complexity increases when storage is added to solar farms',
        'Improper integration can cause performance, safety and warranty issues',
      ],
    },
    {
      kind: 'image',
      src: '/images/utility-detail.png',
      alt: 'Aerial view of rows of utility-scale BESS containers beside a solar farm',
      aspect: '16 / 9',
      caption: 'MWh-class storage assets engineered for grid compliance, safety at scale and a 10–15 year life.',
    },
    {
      kind: 'prose',
      heading: 'The Solunar solution',
      paragraphs: [
        'Solunar provides complete utility-scale ESS farm solutions for large energy infrastructure projects. For utility-scale projects, BESS is not just a battery purchase — it is a full infrastructure system that must be properly designed, integrated, operated and maintained.',
      ],
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'Projects we support',
      lead: 'We support project owners and EPCCs across the utility-scale storage landscape:',
      items: [
        'Large Scale Solar (LSS) projects',
        'CRESS projects',
        'Grid-connected ESS farms',
        'Solar + BESS hybrid plants',
        'Data-centre renewable energy supply',
        'Industrial renewable energy infrastructure',
        'Infrastructure fund-backed energy storage assets',
      ],
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'What we provide',
      lead: "Solunar's utility-scale ESS solution can include:",
      items: [
        'Battery energy storage system selection',
        'Containerised BESS solution',
        'PCS integration',
        'EMS and SCADA integration',
        'Grid compliance support',
        'Solar + storage system architecture',
        'Fire safety and protection system planning',
        'Performance monitoring framework',
        'Testing and commissioning support',
        'O&M planning',
        'Warranty and lifecycle support',
        'Bankability and investor support documentation',
      ],
    },
    {
      kind: 'cards',
      heading: 'Built for developers, EPCCs and investors',
      lead: 'We support — not compete with — the teams delivering large storage assets:',
      columns: 3,
      items: [
        { icon: 'partner', title: 'For EPCCs', text: 'Technical support, product supply, integration and commissioning support behind your team.' },
        { icon: 'developers', title: 'For developers', text: 'Storage solutions designed to improve project value and long-term performance.' },
        { icon: 'proposal', title: 'For funds & banks', text: 'A more bankable asset backed by sound system design, safety planning and O&M capability.' },
      ],
    },
    {
      kind: 'cards',
      heading: 'Key applications',
      lead: 'Utility-scale storage unlocks value across the grid:',
      columns: 3,
      items: [
        { icon: 'sun', title: 'LSS & solar farm integration', text: 'Store solar energy and support better project dispatchability.' },
        { icon: 'integration', title: 'CRESS & corporate renewables', text: 'Enable more reliable renewable supply to corporate and industrial offtakers.' },
        { icon: 'gauge', title: 'Grid support', text: 'Frequency response, grid stability, peak shifting and future grid services.' },
        { icon: 'data-centre', title: 'Data-centre power infrastructure', text: 'High-reliability energy infrastructure for data centres and industrial parks.' },
        { icon: 'recycle', title: 'Renewable asset optimisation', text: 'Improve the long-term value and flexibility of renewable energy assets.' },
      ],
    },
    {
      kind: 'faq',
      items: [
        {
          question: 'What makes a utility-scale ESS bankable?',
          answer:
            'Proven equipment, sound safety and fire design, credible performance and degradation assumptions, a clear O&M strategy and complete technical documentation — the areas Solunar helps developers and lenders de-risk.',
        },
        {
          question: 'Do you support EPCCs as well as asset owners?',
          answer:
            'Yes. Solunar supports developers, asset owners and EPCC contractors with battery selection, integration, monitoring and long-term O&M for utility-scale ESS.',
        },
      ],
    },
    {
      kind: 'cta',
      heading: 'Utility-scale storage is becoming the backbone of renewable energy infrastructure.',
      text: 'Partner with Solunar to design, integrate and operate ESS farms that are safer, smarter and more bankable.',
      actions: [
        { label: 'Talk to Solunar About Your ESS Farm', href: '/contact' },
        { label: 'For Developers & Asset Owners', href: '/solar-bess-developers' },
      ],
    },
  ],
};

export const bessOm: PageContent = {
  slug: '/bess-om-malaysia',
  seoTitle: 'BESS O&M Malaysia | ESS Operations & Maintenance | Solunar',
  metaDescription:
    'Protect your BESS investment with professional ESS O&M. Solunar monitors battery health, temperature, software and safety systems for C&I and utility-scale ESS.',
  navLabel: 'O&M for ESS Projects',
  eyebrow: 'Solutions · O&M',
  h1: 'Protect Your BESS Investment With Professional ESS Operations & Maintenance',
  lead: 'Solunar provides O&M support for commercial, industrial and utility-scale ESS projects to help asset owners maintain safety, performance, uptime and long-term system value.',
  heroActions: [{ label: 'Request an ESS O&M Proposal', href: '/contact' }],
  image: {
    src: '/images/bess-om.png',
    alt: 'Engineer inspecting a BESS container during O&M in Malaysia',
    aspect: '4 / 3',
  },
  primaryKeyword: 'BESS O&M Malaysia',
  schema: { type: 'Service', serviceType: 'BESS operation and maintenance (O&M)' },
  blocks: [
    {
      kind: 'prose',
      heading: 'Why ESS O&M matters',
      paragraphs: [
        'A Battery Energy Storage System is a long-term infrastructure asset. Its value depends not only on the quality of the battery, but on how well the system is operated, monitored, maintained and protected over time.',
        'For ESS assets, O&M is not optional — it is essential.',
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'The risks of neglected O&M',
      lead: 'Without proper O&M, ESS projects may face:',
      items: [
        'Lower system availability',
        'Battery degradation issues',
        'Poor charging and discharging performance',
        'PCS or EMS faults',
        'Thermal management issues',
        'Safety risks',
        'Warranty disputes',
        'Revenue loss from downtime',
        'Reduced investor and lender confidence',
      ],
    },
    {
      kind: 'table',
      heading: 'Solar O&M vs BESS O&M',
      lead: 'BESS O&M is not the same as solar O&M — it adds the battery, software and safety dimension.',
      columns: ['O&M Focus', 'Solar PV', 'BESS'],
      rows: [
        ['Hardware', 'Panels, inverters', 'Battery, PCS, EMS, cooling, fire systems'],
        ['Monitoring', 'Generation, yield', 'SoC, SoH, temperature, alarms'],
        ['Software', 'Inverter firmware', 'EMS logic, firmware coordination'],
        ['Safety', 'Electrical', 'Thermal, fire suppression, emergency shutdown'],
      ],
      caption: 'Comparison of focus areas for solar PV O&M versus BESS O&M.',
    },
    {
      kind: 'image',
      src: '/images/om-detail.png',
      alt: 'Technician in PPE inspecting an open battery storage cabinet with a tablet',
      aspect: '16 / 9',
      caption: 'Proactive O&M protects safety, performance, warranty and bankability across the asset life.',
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'The Solunar O&M approach',
      lead: 'We help asset owners move from reactive maintenance to proactive asset management, focusing on:',
      items: [
        'Preventive maintenance',
        'Remote monitoring',
        'Performance optimisation',
        'Fault detection',
        'Safety inspection',
        'Battery health tracking',
        'PCS and EMS coordination',
        'Incident response support',
        'Warranty and reporting support',
      ],
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'Our O&M scope',
      lead: 'Solunar can support ESS projects with:',
      items: [
        'Regular site inspection',
        'Battery system health check',
        'Thermal management inspection',
        'Fire safety system inspection',
        'PCS performance review',
        'EMS control review',
        'Electrical system inspection',
        'Remote monitoring dashboard',
        'Alarm and fault analysis',
        'Preventive maintenance schedule',
        'Performance reporting',
        'Spare-parts coordination',
        'Technical troubleshooting',
        'Annual maintenance planning',
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'Remote monitoring & performance tracking',
      lead: 'ESS projects must be monitored continuously. Solunar helps track key parameters such as:',
      items: [
        'State of Charge',
        'State of Health',
        'Charge and discharge cycles',
        'Battery temperature',
        'PCS performance',
        'System availability',
        'Fault alarms',
        'Energy throughput',
        'Peak-shaving performance',
        'Solar-charging performance',
        'Battery degradation indicators',
      ],
    },
    {
      kind: 'cards',
      heading: 'O&M for different project types',
      lead: 'We scope O&M to the asset, not a one-size package:',
      columns: 2,
      items: [
        { icon: 'manufacturing', title: 'Commercial & Industrial BESS', text: 'For factories, malls, commercial buildings, industrial parks and EV charging sites.' },
        { icon: 'sun', title: 'Solar + BESS projects', text: 'Where battery performance must be coordinated with solar generation and load.' },
        { icon: 'utilities', title: 'Utility-scale ESS farms', text: 'Large assets requiring structured monitoring, reporting and technical support.' },
        { icon: 'proposal', title: 'Investor-owned ESS assets', text: 'For funds and asset companies needing long-term performance visibility.' },
      ],
    },
    {
      kind: 'faq',
      items: [
        {
          question: 'How is BESS O&M scoped and priced?',
          answer:
            'It depends on asset size, location, monitoring scope and response requirements. Solunar scopes O&M to the project rather than offering a one-size package.',
        },
        {
          question: 'Can you take over O&M for an existing BESS?',
          answer:
            'Often yes — subject to a technical review of the installed battery, PCS, EMS and safety systems and the available documentation.',
        },
      ],
    },
    {
      kind: 'cta',
      heading: 'A BESS is only valuable when it performs safely and consistently over its lifetime.',
      text: 'Let Solunar help you protect your ESS asset with professional O&M support.',
      actions: [
        { label: 'Request an ESS O&M Consultation', href: '/contact' },
        { label: 'Review BESS Safety', href: '/bess-safety' },
      ],
    },
  ],
};

export const bessSafety: PageContent = {
  slug: '/bess-safety',
  seoTitle: 'BESS Safety & Reliability Malaysia | Fire, Thermal & Bankability',
  metaDescription:
    'Safe, reliable and bankable BESS. Solunar reviews battery chemistry, BMS, thermal management, fire detection and suppression for C&I and utility-scale projects.',
  navLabel: 'BESS Safety & Reliability',
  eyebrow: 'Solutions · Safety',
  h1: 'Safe, Reliable and Bankable Battery Energy Storage Systems',
  lead: 'Solunar prioritises safety, reliability and long-term performance in every BESS project — from commercial and industrial systems to utility-scale ESS farms.',
  heroActions: [{ label: 'Speak to a BESS Specialist', href: '/contact' }],
  image: {
    src: '/images/bess-safety.png',
    alt: 'Fire detection and thermal management inside a BESS container',
    aspect: '4 / 3',
  },
  primaryKeyword: 'BESS safety Malaysia',
  schema: { type: 'Service', serviceType: 'BESS safety and reliability review' },
  blocks: [
    {
      kind: 'prose',
      heading: 'Why safety matters',
      paragraphs: [
        'Battery Energy Storage Systems are powerful infrastructure assets. When properly designed, integrated, installed, monitored and maintained, BESS delivers strong commercial and technical value.',
        'But when safety is not properly addressed, BESS projects can face serious risks. For Solunar, safety is not an afterthought — it is part of the system design from day one.',
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'Risks when safety is not properly addressed',
      lead: 'Poorly handled safety creates technical, financial and reputational exposure:',
      items: [
        'Thermal management failure',
        'Fire safety risk',
        'Poor system integration',
        'Improper electrical protection',
        'Battery degradation',
        'Communication failure between battery, PCS and EMS',
        'Unexpected downtime',
        'Warranty and insurance issues',
        'Investor and lender concerns',
      ],
    },
    {
      kind: 'image',
      src: '/images/safety-detail.png',
      alt: 'Interior of a BESS container showing fire suppression, gas detection and thermal management',
      aspect: '16 / 9',
      caption: 'Fire detection, suppression, thermal management and emergency shutdown — sized to the energy on site.',
    },
    {
      kind: 'cards',
      heading: 'Our safety philosophy',
      lead: "Solunar's BESS safety approach is built on four principles:",
      columns: 2,
      items: [
        { icon: 'battery', title: '1. Safe technology selection', text: 'Proven battery technologies and components suitable for C&I and utility-scale applications.' },
        { icon: 'integration', title: '2. Proper system integration', text: 'Battery, PCS, EMS, transformer, switchgear, protection, fire safety and monitoring working together.' },
        { icon: 'gauge', title: '3. Continuous monitoring', text: 'Safety does not end at commissioning — assets must be monitored throughout their life.' },
        { icon: 'om', title: '4. Preventive O&M', text: 'Regular inspection, maintenance, reporting and early fault detection protect reliability.' },
      ],
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'Key safety considerations',
      lead: 'Solunar designs and supports BESS projects with attention to:',
      items: [
        'Battery chemistry and cell quality',
        'Battery management system',
        'Thermal management system',
        'Fire detection and suppression',
        'Container or cabinet design',
        'Electrical protection system',
        'Emergency shutdown system',
        'PCS compatibility',
        'EMS control logic',
        'Site layout and spacing',
        'Ventilation and cooling',
        'Remote monitoring',
        'Operation procedures',
        'Maintenance procedures',
        'Warranty compliance',
      ],
    },
    {
      kind: 'prose',
      heading: 'Reliability starts with integration',
      paragraphs: [
        'Many BESS problems do not come from the battery alone — they come from poor integration. A reliable project must coordinate the battery system, PCS, EMS, SCADA, solar PV, grid connection, load profile, protection relays, fire safety system and remote monitoring platform.',
        "Solunar's role is to ensure these systems are properly integrated so the BESS operates safely and efficiently.",
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'Built for bankability',
      lead: 'A safer, more reliable BESS project directly supports project bankability:',
      items: [
        'Stronger investor confidence',
        'Better lender comfort',
        'Improved insurance acceptance',
        'Lower operational risk',
        'Better long-term asset performance',
        'Reduced downtime',
        'Clearer warranty management',
        'More predictable project returns',
      ],
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'Our safety & reliability support',
      lead: 'Solunar can support customers with:',
      items: [
        'BESS safety review',
        'Technology selection support',
        'System design review',
        'PCS and EMS integration review',
        'Fire safety planning',
        'O&M safety procedures',
        'Remote monitoring framework',
        'Performance and safety reporting',
        'Battery health monitoring',
        'Site inspection checklist',
        'Commissioning support',
        'Incident response planning',
      ],
    },
    {
      kind: 'faq',
      items: [
        {
          question: 'Is LFP chemistry inherently safe?',
          answer:
            'LFP is positioned around thermal stability and is widely chosen for storage, but site safety still depends on full system design — BMS, thermal management, fire systems and integration.',
        },
        {
          question: 'Do you help with insurer and authority requirements?',
          answer:
            'Solunar helps prepare the technical and safety documentation that supports insurer, lender and authority review, in coordination with your EPCC and consultants.',
        },
      ],
    },
    {
      kind: 'cta',
      heading: 'BESS safety is about building a reliable, bankable, long-term asset.',
      text: 'Partner with Solunar to deploy safer and more reliable energy storage solutions.',
      actions: [
        { label: 'Speak to a BESS Specialist', href: '/contact' },
        { label: 'Understand BYD LFP Chemistry', href: '/byd-battery-malaysia' },
      ],
    },
  ],
};

export const solarBessDevelopers: PageContent = {
  slug: '/solar-bess-developers',
  seoTitle: 'Solar + BESS for Developers & EPCCs | Malaysia | Solunar',
  metaDescription:
    'Solunar helps solar developers and EPCCs add BESS without building everything in-house — feasibility, system architecture, bankability, safety and O&M support.',
  navLabel: 'For Developers & Asset Owners',
  eyebrow: 'Solutions · Developers',
  h1: 'Solar + BESS Solutions for Developers, EPCCs & Renewable Energy Platforms',
  lead: 'Helping solar developers unlock higher project value with reliable Battery Energy Storage System integration — from technical design and product selection to commissioning support and long-term O&M.',
  heroActions: [{ label: 'Speak to Our BESS Integration Team', href: '/contact' }],
  image: {
    src: '/images/solar-bess-developers.png',
    alt: 'A large solar-plus-storage farm in Malaysia at golden hour',
    aspect: '4 / 3',
  },
  primaryKeyword: 'Solar BESS for developers Malaysia',
  schema: { type: 'Service', serviceType: 'Solar + BESS support for developers and asset owners' },
  blocks: [
    {
      kind: 'prose',
      heading: 'Solar projects are becoming more competitive — and more complex',
      paragraphs: [
        'Across Malaysia and Southeast Asia, solar developers face growing pressure on margins, pricing and technical requirements. Traditional solar-only projects may no longer be enough to meet the next generation of energy demand.',
        'For large-scale solar farms, CRESS projects, industrial offtake and grid-connected renewable platforms, Battery Energy Storage Systems are becoming a critical part of the project structure.',
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'What solar developers are up against',
      lead: 'Developers increasingly have to design around:',
      items: [
        'Lower EPCC margins',
        'More competitive tender pricing',
        'Grid connection limitations',
        'Curtailment risk',
        'Higher technical requirements from financiers',
        'Demand for firm and dispatchable renewable energy',
        'Complex CRESS, LSS, SELCO and private PPA structures',
        'The need to support data centres and high-load customers',
      ],
    },
    {
      kind: 'image',
      src: '/images/developers-detail.png',
      alt: 'Large solar-plus-storage farm with battery containers integrated at the site edge',
      aspect: '16 / 9',
      caption: 'Storage turns a generation asset into a dispatchable, grid-friendly one that lenders can underwrite.',
    },
    {
      kind: 'prose',
      heading: 'Add BESS without building everything in-house',
      paragraphs: [
        'Solunar works as a specialist BESS system integrator and technology partner for solar developers and EPCC companies. We are not here to compete with developers — we are here to support them.',
        'Our role is to help your project team integrate the right battery system, PCS, EMS, transformer, protection system, communication architecture and O&M strategy into your solar project — whether utility-scale, CRESS, industrial PPA or hybrid.',
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'From solar generation to energy infrastructure',
      lead: 'Solar produces energy; BESS gives developers control over when that energy is used and monetised — creating value through:',
      items: [
        'Energy shifting',
        'Peak shaving',
        'Grid support',
        'Power smoothing',
        'Backup power support',
        'Renewable energy firming',
        'Higher reliability for industrial offtakers',
        'Improved project resilience and flexibility',
      ],
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'Who we serve',
      lead: 'Solunar supports a broad set of project stakeholders:',
      items: [
        'Solar developers',
        'Large-scale solar project owners',
        'CRESS project developers',
        'Commercial and industrial solar EPCCs',
        'Renewable energy platforms',
        'Infrastructure funds',
        'Solar asset owners',
        'Industrial park developers',
        'Data-centre energy solution providers',
        'Utilities and grid-connected project owners',
      ],
    },
    {
      kind: 'steps',
      heading: 'Our scope of support',
      lead: 'Complete BESS integration support across the project lifecycle:',
      items: [
        { title: 'Technical feasibility & concept design', text: 'BESS sizing, use case, duration, PCS capacity, layout, single-line review and grid considerations.' },
        { title: 'Product selection & system architecture', text: 'Battery, PCS, EMS, BMS, transformer/MV, protection, fire safety, SCADA and monitoring — AC- or DC-coupled.' },
        { title: 'Commercial & financial structuring', text: 'CAPEX structure, ROI, PPA enhancement, bankability, degradation and lifecycle assumptions.' },
        { title: 'Safety, compliance & reliability review', text: 'Chemistry review, thermal-runaway mitigation, fire suppression, protection coordination and emergency response.' },
        { title: 'Commissioning & O&M support', text: 'Testing, commissioning, remote monitoring, battery-health tracking, warranty coordination and optimisation.' },
      ],
    },
    {
      kind: 'cards',
      heading: 'Why developers work with Solunar',
      lead: 'A specialist partner that strengthens — never replaces — your team:',
      columns: 3,
      items: [
        { icon: 'integration', title: 'Specialist integration', text: 'We focus on BESS design, integration and operation, not just product supply.' },
        { icon: 'partner', title: 'Support, not competition', text: 'We work behind developers and EPCCs as a technology and integration partner.' },
        { icon: 'layers', title: 'Multi-brand flexibility', text: 'We integrate different battery, PCS and EMS solutions to fit the project.' },
        { icon: 'battery', title: 'BYD & GoodWe ecosystem', text: 'Access to leading BESS, inverter and PCS technologies.' },
        { icon: 'proposal', title: 'Bankability-focused', text: 'We help present projects that investors, lenders and offtakers can underwrite.' },
        { icon: 'safety', title: 'Safety-first design', text: 'Fire safety, reliability, monitoring and long-term operational stability come first.' },
      ],
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'Solar + BESS use cases',
      lead: 'Solunar supports BESS integration for:',
      items: [
        'Large Scale Solar projects',
        'CRESS projects',
        'Commercial and industrial solar PPAs',
        'Industrial parks',
        'Data centres',
        'Utility-scale ESS farms',
        'Behind-the-meter solar + storage',
        'Peak-shaving projects',
        'Power-expansion projects',
        'Grid-constrained sites',
        'Renewable energy firming',
        'Energy shifting and dispatch optimisation',
      ],
    },
    {
      kind: 'faq',
      items: [
        {
          question: 'Does Solunar replace our EPCC or developer team?',
          answer:
            'No. Solunar supplies the BESS technology and integration layer behind your team — you keep the project, the client and execution.',
        },
        {
          question: 'Can you support investor and lender due diligence?',
          answer:
            'Yes — Solunar can provide technical due-diligence materials, performance and degradation assumptions, safety summaries and an O&M strategy to support financing.',
        },
      ],
    },
    {
      kind: 'cta',
      heading: "Planning a Solar + BESS project? Let's build it together.",
      text: 'Whether you are preparing for LSS, CRESS, SELCO, private PPA, industrial solar or utility-scale storage, Solunar can support your project with technical, commercial and integration expertise.',
      actions: [
        { label: 'Talk to Our Solar + BESS Team', href: '/contact' },
        { label: 'Utility-Scale ESS Support', href: '/utility-scale-ess-malaysia' },
      ],
    },
  ],
};

export const localAssembly: PageContent = {
  slug: '/local-bess-assembly',
  seoTitle: 'Future Local BESS Assembly Malaysia | Solunar Localisation',
  metaDescription:
    'Solunar is building towards local BESS assembly, integration and support for Malaysia and Southeast Asia — faster delivery, better after-sales and stronger local capability.',
  navLabel: 'Future Local Assembly',
  eyebrow: 'Solutions · Localisation',
  h1: 'Future Local Assembly for Battery Energy Storage Systems',
  lead: 'Building a stronger local BESS supply chain for Malaysia and Southeast Asia — moving beyond distribution and system integration towards local assembly, customisation and value-added support.',
  heroActions: [{ label: 'Explore Local Assembly Opportunities', href: '/contact' }],
  image: {
    src: '/images/local-assembly.png',
    alt: 'Technicians assembling battery energy storage cabinets on a factory floor in Malaysia',
    aspect: '4 / 3',
  },
  primaryKeyword: 'local BESS assembly Malaysia',
  schema: { type: 'Service', serviceType: 'Future local BESS assembly and support' },
  blocks: [
    {
      kind: 'prose',
      heading: 'Malaysia needs a stronger local energy-storage supply chain',
      paragraphs: [
        'The rapid growth of solar, BESS, data centres, industrial electrification and grid modernisation is creating strong demand for reliable energy storage solutions. Yet many BESS projects still depend heavily on imported, fully assembled systems.',
        'As Malaysia develops more renewable energy and storage projects, the market will require stronger local participation.',
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'The cost of import dependence',
      lead: 'Relying on imported, fully assembled systems creates challenges such as:',
      items: [
        'Longer delivery timelines',
        'Foreign-exchange exposure',
        'Limited local customisation',
        'Higher logistics costs',
        'Limited local technical support',
        'Dependency on overseas production schedules',
        'Harder after-sales service and spare-parts planning',
        'Limited local value creation',
      ],
    },
    {
      kind: 'image',
      src: '/images/localassembly-detail.png',
      alt: 'Workers assembling and integrating battery energy storage cabinets on a production floor',
      aspect: '16 / 9',
      caption: 'Building towards local assembly, integration and support to shorten delivery and strengthen after-sales.',
    },
    {
      kind: 'prose',
      heading: 'From importing products to building local capability',
      paragraphs: [
        "Solunar's local-assembly strategy is to build capability step by step — starting with system integration, testing and localisation, then assembly support, and eventually selected local assembly of BESS-related solutions.",
        'This lets us create local value while maintaining product reliability, safety standards and global technology partnerships.',
      ],
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'What future local assembly may include',
      lead: 'Local value, global technology — potential activities include:',
      items: [
        'Battery cabinet assembly',
        'Containerised BESS integration',
        'PCS and EMS integration',
        'Wiring and control-panel assembly',
        'Thermal management system integration',
        'Fire safety system integration',
        'Factory acceptance testing',
        'System configuration and software setup',
        'Local branding and project customisation',
        'Spare-parts and after-sales support centre',
        'O&M and technical training centre',
      ],
    },
    {
      kind: 'steps',
      heading: 'Our roadmap for local BESS capability',
      lead: 'A practical, scalable four-stage roadmap:',
      items: [
        { title: 'Stage 1 — Distribution & integration', text: 'Integrate proven international BESS solutions for the Malaysian market, with design, engineering and O&M support.' },
        { title: 'Stage 2 — Local testing & configuration', text: 'Factory acceptance support, local configuration, pre-commissioning checks, battery-health verification and training.' },
        { title: 'Stage 3 — Local assembly & customisation', text: 'Cabinet and container assembly, control-panel and auxiliary integration, fire and thermal systems, project-specific packaging.' },
        { title: 'Stage 4 — Regional BESS platform', text: 'Serve Malaysia and Southeast Asia across C&I, utility-scale, solar + BESS, microgrids and regional O&M.' },
      ],
    },
    {
      kind: 'list',
      variant: 'check',
      columns: 2,
      heading: 'Why local capability matters for customers',
      lead: 'Local assembly is about trust, speed and serviceability across the value chain:',
      items: [
        'Faster project delivery',
        'Better local technical support',
        'Improved spare-parts availability',
        'More flexible system customisation',
        'Reduced logistics complexity',
        'Potential cost optimisation',
        'Higher local-content participation',
        'Stronger after-sales service',
        'Better responsiveness during execution',
        'Greater confidence for long-term O&M',
      ],
    },
    {
      kind: 'note',
      text: 'Local assembly must never compromise safety or reliability. Our approach prioritises approved battery technology, reliable architecture, electrical protection, thermal management, fire detection and suppression, quality control, factory and site acceptance testing, and compliance with applicable standards — combining global technology quality with local execution strength. These are forward-looking opportunities; current engagement focuses on technology distribution, system integration and O&M support.',
    },
    {
      kind: 'list',
      variant: 'inline',
      heading: 'Partnership opportunities',
      lead: 'Solunar is open to working with:',
      items: [
        'Battery manufacturers',
        'PCS manufacturers',
        'EMS technology providers',
        'Solar developers',
        'EPCC companies',
        'Infrastructure funds',
        'Industrial park owners',
        'Data-centre developers',
        'Government agencies',
        'Technical training institutions',
        'Local fabricators and engineering partners',
        'Financial institutions supporting energy-transition projects',
      ],
    },
    {
      kind: 'faq',
      items: [
        {
          question: 'Is local assembly available today?',
          answer:
            "These are forward-looking opportunities. Solunar's current engagement focuses on technology distribution, system integration and O&M support, while building towards localised assembly.",
        },
      ],
    },
    {
      kind: 'cta',
      heading: 'Interested in local BESS assembly or strategic partnership?',
      text: "Talk to Solunar about participating in Malaysia's growing local clean-energy storage capability.",
      actions: [
        { label: 'Discuss Partnership Opportunities', href: '/contact' },
        { label: 'About Solunar Energy', href: '/about' },
      ],
    },
  ],
};
