import {
  Activity,
  Battery,
  BatteryCharging,
  Boxes,
  Building,
  Building2,
  CircuitBoard,
  Cpu,
  FileText,
  Flame,
  Fuel,
  Gauge,
  GitBranch,
  Handshake,
  Hotel,
  Layers,
  LineChart,
  Network,
  Plug,
  Power,
  Recycle,
  Server,
  Settings2,
  ShieldCheck,
  ShoppingBag,
  Snowflake,
  Sun,
  Thermometer,
  Warehouse,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Maps semantic content keys to a single, consistent lucide icon set. */
export const iconRegistry: Record<string, LucideIcon> = {
  battery: Battery,
  'battery-charging': BatteryCharging,
  inverter: Zap,
  integration: Network,
  'multi-brand': GitBranch,
  pcs: CircuitBoard,
  ems: Cpu,
  om: Wrench,
  safety: ShieldCheck,
  peak: Activity,
  gauge: Gauge,
  expansion: Power,
  developers: LineChart,
  assembly: Boxes,
  layers: Layers,
  settings: Settings2,
  proposal: FileText,
  partner: Handshake,
  sun: Sun,
  thermal: Thermometer,
  fire: Flame,
  recycle: Recycle,
  // industries
  manufacturing: Building,
  'cold-storage': Snowflake,
  'data-centre': Server,
  'ev-charging': Plug,
  'industrial-park': Building2,
  mall: ShoppingBag,
  hotel: Hotel,
  petrol: Fuel,
  utilities: Network,
  warehouse: Warehouse,
};

export function getIcon(name?: string): LucideIcon {
  if (name && iconRegistry[name]) return iconRegistry[name];
  return Layers;
}
